import styles from './post-detail.module.scss';
import { useParams } from 'react-router-dom';

export const PostDetail = () => {
    const { postId } = useParams();
    return <div className={styles.detailContainer}>
        <article className={styles.detailContent}>
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project.

            Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice.
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            In this blog, I will cover how to create a 'bcrypt" module for use in a Ruby on Rails project. Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not, this used to be the case. However, this is no longer safe and NOT considered to be best practice. The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
            The code below is a module. I have called this module "Crud". The methods in this module can be easily called on from other classes or files:
        </article>
        <aside className={styles.sideBar}>
            <div className={styles.profile}>
                Bcrypt uses the MD5 algorithm and adds in a salt to it in order to hash passwords. This is important because as developers we do not want passwords to be stored as regular old strings. Believe it or not
            </div>
        </aside>
    </div>;
}